/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

#include <iostream>

using namespace std;

int main(){
    long int sum = 0, fibonacci = 0, array[2] = {0,1}; // Variables definition

    do{
        fibonacci = array[0] + array[1]; // Suming the last two Fibonacci terms
        cout << fibonacci << endl;
        array[0] = array[1];
        array[1] = fibonacci;
        if(fibonacci%2 == 0){ // Testing if the Fibonacci number is even
            sum += fibonacci;
        }
    }while(fibonacci < 4000000); // Runs the loop until Fibonacci number is smaller than 4000000
    cout <<"The sum of all even Fibonnaci numbers smaller then 4000000 is " << sum << endl;
    return 0;
}